- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   system_accprofile_list:
      - name: "noaccess"
        comments: "noaccess"
        authgrp: "none"
        ftviewgrp: "none"
        fwgrp: "none"
        loggrp: "none"
        netgrp: "none"
        secfabgrp: "none"
        sysgrp: "none"
        utmgrp: "none"
        vpngrp: "none"
        wanoptgrp: "none"
        wifi: "none"
      - name: "Read_only"
        comments: "Readonly_profile"
        authgrp: "read"
        ftviewgrp: "read"
        fwgrp: "read"
        loggrp: "read"
        netgrp: "read"
        secfabgrp: "read"
        sysgrp: "read"
        utmgrp: "read"
        vpngrp: "read"
        wanoptgrp: "read"
        wifi: "read"
      - name: "Admin_profile"
        comments: "Admin_profile"
        authgrp: "read-write"
        ftviewgrp: "read-write"
        fwgrp: "read-write"
        loggrp: "read-write"
        netgrp: "read-write"
        secfabgrp: "read-write"
        sysgrp: "read-write"
        utmgrp: "read-write"
        vpngrp: "read-write"
        wanoptgrp: "read-write"
        wifi: "read-write"
  tasks:
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        system_global:
            hostname: "FW01"
            admintimeout: "22"
   - name: SNMP system info configuration.
     fortios_system_snmp_sysinfo:
      vdom:  "{{ vdom }}"
      system_snmp_sysinfo:
        contact_info: "support team"
        description: "SNMP test"
        location: "SNMP LOCATION"
        status: "enable"
   - name: SNMP community configuration.
     fortios_system_snmp_community:
      vdom:  "{{ vdom }}"
      state: "present"
      system_snmp_community:
        hosts:
         -
            ha_direct: "enable"
            host_type: "any"
            id:  "1"
            ip: "10.2.1.1"
        id:  "1"
        name: "default_name_17"
        query_v2c_port: "162"
        query_v2c_status: "enable"
        status: "enable"
        trap_v2c_lport: "161"
        trap_v2c_rport: "161"
        trap_v2c_status: "enable"
   - name: Global settings for remote syslog server.
     fortios_log_syslogd_setting:
      vdom:  "{{ vdom }}"
      log_syslogd_setting:
        facility: "kernel"
        format: "default"
        mode: "udp"
        port: "514"
        server: "192.168.100.40"
        status: "enable"
   - name: Configure DNS.
     fortios_system_dns:
      vdom:  "{{ vdom }}"
      system_dns:
        domain: "fortinet.com"
        primary: "192.168.100.40"
   - name: Configure system NTP information.
     fortios_system_ntp:
      vdom:  "{{ vdom }}"
      system_ntp:
        ntpserver:
         -
            server: "192.168.100.40"
            id: "1"
        ntpsync: "enable"
        syncinterval: "15"
        type: "custom"
   - name: Configure access profiles for system administrators
     fortinet.fortios.fortios_system_accprofile:
       state: present
       system_accprofile:
         name: "{{ item.name }}"
         comments: "{{ item.comments }}"
         authgrp: "{{ item.authgrp }}"
         ftviewgrp: "{{ item.ftviewgrp }}"
         fwgrp: "{{ item.fwgrp }}"
         loggrp: "{{ item.loggrp }}"
         netgrp: "{{ item.netgrp }}"
         secfabgrp: "{{ item.secfabgrp }}"
         sysgrp: "{{ item.sysgrp }}"
         utmgrp: "{{ item.utmgrp }}"
         vpngrp: "{{ item.vpngrp }}"
         wanoptgrp: "{{ item.wanoptgrp }}"
         wifi: "{{ item.wifi }}"
     loop: "{{ system_accprofile_list }}"
   - name: Configure TACACS+ server entries.
     fortios_user_tacacsplus:
      vdom:  "{{ vdom }}"
      state: "present"
      user_tacacsplus:
        authorization: "enable"
        key: "Fortinet"
        name: "TACACS1"
        secondary_key: "Fortinet"
        secondary_server: "2.2.2.2"
        server: "1.1.1.1"
   - name: Configure user groups.
     fortios_user_group:
      vdom:  "{{ vdom }}"
      state: "present"
      user_group:
        member:
         -
            name: "TACACS1"
        name: "TACACS+"
   - name: Configure admin users.
     fortios_system_admin:
      vdom:  "{{ vdom }}"
      state: "present"
      system_admin:
        accprofile: "noaccess"
        accprofile_override: "enable"
        name: "TACACS_USER"
        remote_auth: "enable"
        remote_group: "TACACS+"
        trusthost1: "10.0.0.0 255.0.0.0"
        two_factor: "disable"
        vdom:
         -
            name: "root"
        wildcard: "enable"